// Code generated by goark-orm; DO NOT EDIT.
// 本文件由 goark-orm 生成，请勿手工修改。

package minimal

import (
	"context"
	orm "goark.dev/orm"
)

func goarkORMUserEntityMeta() orm.EntityMeta {
	return orm.EntityMeta{TypeName: "User", Table: "sys_user", Columns: []orm.ColumnMeta{{FieldName: "ID", FieldType: "int64", ColumnName: "id", PrimaryKey: true, AutoIncrement: true}, {FieldName: "Name", FieldType: "string", ColumnName: "name", Nullable: goarkORMBoolPtr(false), Size: goarkORMIntPtr(64)}, {FieldName: "Status", FieldType: "string", ColumnName: "status", Nullable: goarkORMBoolPtr(false), Size: goarkORMIntPtr(32)}}}
}

type goarkORMUserFields struct {
	ID     orm.Field[User]
	Name   orm.Field[User]
	Status orm.Field[User]
}

// UserFields 暴露 User 的类型安全字段常量。
var UserFields = goarkORMUserFields{
	ID:     orm.NewField[User]("id"),
	Name:   orm.NewField[User]("name"),
	Status: orm.NewField[User]("status"),
}

type goarkORMUserTypedFields struct {
	ID     orm.TypedField[User, int64]
	Name   orm.TypedField[User, string]
	Status orm.TypedField[User, string]
}

// UserTypedFields 暴露 User 的类型化字段常量。
var UserTypedFields = goarkORMUserTypedFields{
	ID:     orm.NewTypedField[User, int64]("id"),
	Name:   orm.NewTypedField[User, string]("name"),
	Status: orm.NewTypedField[User, string]("status"),
}

func goarkORMScanUserRow(ctx context.Context, columns []string, row orm.RowScannerRow, dest any) error {
	_ = ctx
	user, ok := dest.(*User)
	if !ok || user == nil {
		return &orm.MappingError{Message: "row scanner destination must be *User"}
	}
	var goarkORMTargets [3]any
	targets := goarkORMTargets[:]
	if len(columns) > len(targets) {
		targets = make([]any, len(columns))
	} else {
		targets = targets[:len(columns)]
	}
	for index, column := range columns {
		switch goarkORMColumnKey(column) {
		case "id":
			targets[index] = &user.ID
		case "name":
			targets[index] = &user.Name
		case "status":
			targets[index] = &user.Status
		default:
			var discard any
			targets[index] = &discard
		}
	}
	if err := row.Scan(targets...); err != nil {
		return err
	}
	return nil
}

// NewUserBaseMapper 创建 User 的通用 BaseMapper。
func NewUserBaseMapper(session orm.StatementSession) (*orm.BaseMapper[User, int64], error) {
	return orm.NewBaseMapper[User, int64](session, goarkORMUserEntityMeta())
}

// NewUserService 创建 User 的通用 Service。
func NewUserService(session orm.StatementSession) (*orm.Service[User, int64], error) {
	mapper, err := NewUserBaseMapper(session)
	if err != nil {
		return nil, err
	}
	return orm.NewService[User, int64](mapper)
}

func RegisterGoarkORMMetadata(registry *orm.Registry) error {
	if err := registry.RegisterEntity(goarkORMUserEntityMeta()); err != nil {
		return err
	}
	if err := registry.RegisterRowScanner("User", orm.RowScannerFunc(goarkORMScanUserRow)); err != nil {
		return err
	}
	if err := registry.RegisterMapper(orm.MapperMeta{TypeName: "UserMapper", Namespace: "example.minimal.UserMapper", ImplTypeName: "goarkORMUserMapper", ResultMaps: []orm.ResultMapMeta{}, Statements: []orm.StatementMeta{{ID: "FindByID", Namespace: "example.minimal.UserMapper", FullName: "example.minimal.UserMapper.FindByID", Command: orm.StatementCommand("select"), Source: orm.StatementSource("annotation"), SQL: "select id, name, status from sys_user where id = #{id}", ResultType: "User", ParameterType: "int64", Parameters: []string{"id"}}, {ID: "ListByStatus", Namespace: "example.minimal.UserMapper", FullName: "example.minimal.UserMapper.ListByStatus", Command: orm.StatementCommand("select"), Source: orm.StatementSource("annotation"), SQL: "select id, name, status from sys_user where status = #{status}", ResultType: "User", ParameterType: "string", Parameters: []string{"status"}}}}); err != nil {
		return err
	}
	return nil
}

func goarkORMBoolPtr(value bool) *bool {
	return &value
}

func goarkORMIntPtr(value int) *int {
	return &value
}

func goarkORMColumnKey(value string) string {
	runes := make([]rune, 0, len(value))
	for _, item := range value {
		switch item {
		case '_', '-', '.', ' ', '\t', '\n', '\r':
			continue
		}
		if item >= 'A' && item <= 'Z' {
			item += 'a' - 'A'
		}
		runes = append(runes, item)
	}
	return string(runes)
}

type goarkORMUserMapper struct {
	session orm.Session
}

func NewUserMapper(session orm.Session) UserMapper {
	return &goarkORMUserMapper{session: session}
}

func (m *goarkORMUserMapper) FindByID(ctx context.Context, id int64) (*User, error) {
	var out *User
	err := m.session.QueryOne(ctx, "example.minimal.UserMapper.FindByID", orm.NamedArgs{"_parameter": id, "id": id, "param1": id}, &out)
	return out, err
}

func (m *goarkORMUserMapper) ListByStatus(ctx context.Context, status string, page orm.PageRequest) (orm.Page[User], error) {
	return orm.QueryPage[User](ctx, m.session, "example.minimal.UserMapper.ListByStatus", orm.NamedArgs{"_parameter": status, "param1": status, "status": status}, page)
}
