package ormcli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCommand_whenGenerateORMToStdout_shouldPrintGeneratedSource(t *testing.T) {
	dir := writeORMFixture(t)
	var stdout bytes.Buffer
	var stderr bytes.Buffer

	code := Main([]string{
		"generate", "orm",
		"--dir", dir,
	}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d, stderr=%s", code, stderr.String())
	}
	output := stdout.String()
	expected := []string{
		"// Code generated by goark-orm; DO NOT EDIT.",
		"package sample",
		"func RegisterGoarkORMMetadata(registry *orm.Registry) error",
		"Namespace: \"system.user.UserMapper\"",
		"func NewUserMapper(session orm.Session) UserMapper",
	}
	for _, fragment := range expected {
		if !strings.Contains(output, fragment) {
			t.Fatalf("generated ORM output missing %q:\n%s", fragment, output)
		}
	}
	if stderr.Len() != 0 {
		t.Fatalf("stderr should be empty, got %q", stderr.String())
	}
}

func TestCommand_whenGenerateORMToFile_shouldWriteFileAndReportToStderr(t *testing.T) {
	dir := writeORMFixture(t)
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	output := filepath.Join(dir, "zz_goark_orm_sample_gen.go")

	code := Main([]string{
		"gen", "orm",
		"--dir", dir,
		"--output", output,
	}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d, stderr=%s", code, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout should be empty, got %q", stdout.String())
	}
	if !strings.Contains(stderr.String(), "generated "+output) {
		t.Fatalf("expected generated path on stderr, got %q", stderr.String())
	}
	data, err := os.ReadFile(output)
	if err != nil {
		t.Fatalf("read generated ORM file failed: %v", err)
	}
	if !strings.Contains(string(data), "type goarkORMUserMapper struct") {
		t.Fatalf("unexpected generated ORM file:\n%s", string(data))
	}
}

func TestCommand_whenHelpRequested_shouldReturnSuccess(t *testing.T) {
	var stdout bytes.Buffer
	var stderr bytes.Buffer

	code := Main([]string{"generate", "orm", "--help"}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d", code)
	}
	if !strings.Contains(stdout.String(), "goark-orm generate orm [pattern] [flags]") {
		t.Fatalf("expected ORM help in stdout, got %q", stdout.String())
	}
	if stderr.Len() != 0 {
		t.Fatalf("stderr should be empty, got %q", stderr.String())
	}
}

func TestCommand_whenVersionRequested_shouldPrintVersion(t *testing.T) {
	var stdout bytes.Buffer
	var stderr bytes.Buffer

	code := Command{Out: &stdout, Err: &stderr, Version: "test"}.Run([]string{"--version"})

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d", code)
	}
	if strings.TrimSpace(stdout.String()) != "goark-orm test" {
		t.Fatalf("unexpected version output %q", stdout.String())
	}
	if stderr.Len() != 0 {
		t.Fatalf("stderr should be empty, got %q", stderr.String())
	}
}

func writeORMFixture(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "mapper.go"), []byte(`package sample

import "context"

//goark-orm:entity(table="sys_user")
type User struct {
	ID int64 `+"`"+`goark-orm:"column='id';primary-key=true;auto-increment=true"`+"`"+`
	Name string `+"`"+`goark-orm:"column='name'"`+"`"+`
}

//goark-orm:mapper(namespace="system.user.UserMapper")
type UserMapper interface {
	//goark-orm:select(sql="select id, name from sys_user where id = #{id}")
	FindByID(ctx context.Context, id int64) (*User, error)
}
`), 0o644); err != nil {
		t.Fatalf("write ORM source failed: %v", err)
	}
	return dir
}
