package ormcli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestCommand_whenGenerateORMToStdout_shouldPrintGeneratedSource(t *testing.T) {
	dir := writeORMFixture(t)
	var stdout bytes.Buffer
	var stderr bytes.Buffer

	code := Main([]string{
		"generate", "orm",
		"--dir", dir,
	}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d, stderr=%s", code, stderr.String())
	}
	output := stdout.String()
	expected := []string{
		"// Code generated by goark-orm; DO NOT EDIT.",
		"package sample",
		"func RegisterGoarkORMMetadata(registry *orm.Registry) error",
		"var UserFields = goarkORMUserFields",
		"func NewUserBaseMapper(session orm.StatementSession) (*orm.BaseMapper[User, int64], error)",
		"Namespace: \"system.user.UserMapper\"",
		"func NewUserMapper(session orm.Session) UserMapper",
	}
	for _, fragment := range expected {
		if !strings.Contains(output, fragment) {
			t.Fatalf("generated ORM output missing %q:\n%s", fragment, output)
		}
	}
	if stderr.Len() != 0 {
		t.Fatalf("stderr should be empty, got %q", stderr.String())
	}
}

func TestCommand_whenGenerateORMToFile_shouldWriteFileAndReportToStderr(t *testing.T) {
	dir := writeORMFixture(t)
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	output := filepath.Join(dir, "zz_goark_orm_sample_gen.go")

	code := Main([]string{
		"gen", "orm",
		"--dir", dir,
		"--output", output,
	}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d, stderr=%s", code, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout should be empty, got %q", stdout.String())
	}
	if !strings.Contains(stderr.String(), "generated "+output) {
		t.Fatalf("expected generated path on stderr, got %q", stderr.String())
	}
	data, err := os.ReadFile(output)
	if err != nil {
		t.Fatalf("read generated ORM file failed: %v", err)
	}
	outputText := string(data)
	if !strings.Contains(outputText, "type goarkORMUserMapper struct") {
		t.Fatalf("unexpected generated ORM file:\n%s", string(data))
	}
	if !strings.Contains(outputText, "var UserFields = goarkORMUserFields") {
		t.Fatalf("generated ORM file should contain field constants:\n%s", outputText)
	}
}

func TestCommand_whenGenerateORMToFileUnchanged_shouldSkipWriteAndReportToStderr(t *testing.T) {
	dir := writeORMFixture(t)
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	output := filepath.Join(dir, "zz_goark_orm_sample_gen.go")

	code := Main([]string{
		"gen", "orm",
		"--dir", dir,
		"--output", output,
	}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("initial generate failed with code %d, stderr=%s", code, stderr.String())
	}
	past := time.Unix(1_700_000_000, 0)
	if err := os.Chtimes(output, past, past); err != nil {
		t.Fatalf("set generated file time failed: %v", err)
	}
	stdout.Reset()
	stderr.Reset()

	code = Main([]string{
		"gen", "orm",
		"--dir", dir,
		"--output", output,
	}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d, stderr=%s", code, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout should be empty, got %q", stdout.String())
	}
	if !strings.Contains(stderr.String(), "unchanged "+output) {
		t.Fatalf("expected unchanged path on stderr, got %q", stderr.String())
	}
	info, err := os.Stat(output)
	if err != nil {
		t.Fatalf("stat generated ORM file failed: %v", err)
	}
	if !info.ModTime().Equal(past) {
		t.Fatalf("unchanged generated file should not be rewritten, got modtime %s", info.ModTime())
	}
}

func TestWriteGeneratedFile_whenContentChanges_shouldReplaceWithoutTempFileLeak(t *testing.T) {
	dir := t.TempDir()
	output := filepath.Join(dir, "zz_goark_orm_sample_gen.go")

	result, err := writeGeneratedFile(output, []byte("old\n"))
	if err != nil {
		t.Fatalf("initial write failed: %v", err)
	}
	if !result.Changed || result.Path != filepath.Clean(output) {
		t.Fatalf("unexpected initial write result %#v", result)
	}
	result, err = writeGeneratedFile(output, []byte("new\n"))
	if err != nil {
		t.Fatalf("replace write failed: %v", err)
	}
	if !result.Changed {
		t.Fatalf("changed content should be written")
	}
	data, err := os.ReadFile(output)
	if err != nil {
		t.Fatalf("read generated file failed: %v", err)
	}
	if string(data) != "new\n" {
		t.Fatalf("unexpected generated file content %q", data)
	}
	matches, err := filepath.Glob(filepath.Join(dir, ".*.tmp-*"))
	if err != nil {
		t.Fatalf("glob temp files failed: %v", err)
	}
	if len(matches) != 0 {
		t.Fatalf("temporary generated files leaked: %#v", matches)
	}
}

func TestCommand_whenGenerateORMDryRun_shouldNotWriteFile(t *testing.T) {
	dir := writeORMFixture(t)
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	output := filepath.Join(dir, "zz_goark_orm_sample_gen.go")

	code := Main([]string{
		"generate", "orm",
		"--dir", dir,
		"--output", output,
		"--dry-run",
	}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d, stderr=%s", code, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout should be empty, got %q", stdout.String())
	}
	if !strings.Contains(stderr.String(), "dry-run generated "+output) {
		t.Fatalf("expected dry-run path on stderr, got %q", stderr.String())
	}
	if _, err := os.Stat(output); !os.IsNotExist(err) {
		t.Fatalf("dry-run should not write output, stat err=%v", err)
	}
}

func TestCommand_whenGenerateORMValidate_shouldOnlyValidate(t *testing.T) {
	dir := writeORMFixture(t)
	var stdout bytes.Buffer
	var stderr bytes.Buffer

	code := Main([]string{
		"generate", "orm",
		"--dir", dir,
		"--validate",
	}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d, stderr=%s", code, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout should be empty, got %q", stdout.String())
	}
	if !strings.Contains(stderr.String(), "validated "+dir) {
		t.Fatalf("expected validation output, got %q", stderr.String())
	}
}

func TestCommand_whenGenerateORMCheck_shouldCompareGeneratedFile(t *testing.T) {
	dir := writeORMFixture(t)
	output := filepath.Join(dir, "zz_goark_orm_sample_gen.go")
	var stdout bytes.Buffer
	var stderr bytes.Buffer

	code := Main([]string{
		"generate", "orm",
		"--dir", dir,
		"--output", output,
	}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("initial generate failed with code %d, stderr=%s", code, stderr.String())
	}
	stdout.Reset()
	stderr.Reset()

	code = Main([]string{
		"generate", "orm",
		"--dir", dir,
		"--output", output,
		"--check",
	}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected check exit code 0, got %d, stderr=%s", code, stderr.String())
	}
	if !strings.Contains(stderr.String(), "checked "+output) {
		t.Fatalf("expected checked output, got %q", stderr.String())
	}

	if err := os.WriteFile(output, []byte("stale"), 0o644); err != nil {
		t.Fatalf("write stale output failed: %v", err)
	}
	stdout.Reset()
	stderr.Reset()
	code = Main([]string{
		"generate", "orm",
		"--dir", dir,
		"--output", output,
		"--check",
	}, &stdout, &stderr)

	if code != 1 {
		t.Fatalf("expected stale check exit code 1, got %d", code)
	}
	if !strings.Contains(stderr.String(), "generated file out of date") {
		t.Fatalf("expected stale check message, got %q", stderr.String())
	}
}

func TestCommand_whenGenerateORMDiff_shouldPrintGeneratedDiff(t *testing.T) {
	dir := writeORMFixture(t)
	output := filepath.Join(dir, "zz_goark_orm_sample_gen.go")
	if err := os.WriteFile(output, []byte("stale\n"), 0o644); err != nil {
		t.Fatalf("write stale output failed: %v", err)
	}
	var stdout bytes.Buffer
	var stderr bytes.Buffer

	code := Main([]string{
		"generate", "orm",
		"--dir", dir,
		"--output", output,
		"--diff",
	}, &stdout, &stderr)

	if code != 1 {
		t.Fatalf("expected diff exit code 1, got %d", code)
	}
	diff := stdout.String()
	if !strings.Contains(diff, "--- "+output) || !strings.Contains(diff, "+++ generated") || !strings.Contains(diff, "-stale") {
		t.Fatalf("unexpected diff output:\n%s", diff)
	}
	if stderr.Len() != 0 {
		t.Fatalf("stderr should be empty, got %q", stderr.String())
	}
}

func TestCommand_whenGenerateORMModesConflict_shouldReject(t *testing.T) {
	dir := writeORMFixture(t)
	var stdout bytes.Buffer
	var stderr bytes.Buffer

	code := Main([]string{
		"generate", "orm",
		"--dir", dir,
		"--dry-run",
		"--diff",
	}, &stdout, &stderr)

	if code != 2 {
		t.Fatalf("expected exit code 2, got %d", code)
	}
	if !strings.Contains(stderr.String(), "不能同时使用") {
		t.Fatalf("expected mode conflict error, got %q", stderr.String())
	}
}

func TestCommand_whenGenerateORMConfigProvided_shouldGenerateConfiguredPackages(t *testing.T) {
	root := t.TempDir()
	dir := filepath.Join(root, "internal", "user")
	writeORMFixtureAt(t, dir)
	configPath := filepath.Join(root, "goark-orm.json")
	output := filepath.Join(root, "generated", "user_gen.go")
	if err := os.WriteFile(configPath, []byte(`{
  "typeHandlers": ["json"],
  "packages": [
    {
      "dir": "internal/user",
      "output": "generated/user_gen.go"
    }
  ]
}`), 0o644); err != nil {
		t.Fatalf("write config failed: %v", err)
	}
	var stdout bytes.Buffer
	var stderr bytes.Buffer

	code := Main([]string{
		"generate", "orm",
		"--config", configPath,
	}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d, stderr=%s", code, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout should be empty, got %q", stdout.String())
	}
	if !strings.Contains(stderr.String(), "generated "+output) {
		t.Fatalf("expected generated path on stderr, got %q", stderr.String())
	}
	data, err := os.ReadFile(output)
	if err != nil {
		t.Fatalf("read generated ORM file failed: %v", err)
	}
	if !strings.Contains(string(data), "func NewUserMapper(session orm.Session) UserMapper") {
		t.Fatalf("generated ORM file missing mapper implementation:\n%s", data)
	}
}

func TestCommand_whenGenerateORMConfigWithPattern_shouldReject(t *testing.T) {
	configPath := filepath.Join(t.TempDir(), "goark-orm.json")
	if err := os.WriteFile(configPath, []byte(`{"dir":"."}`), 0o644); err != nil {
		t.Fatalf("write config failed: %v", err)
	}
	var stdout bytes.Buffer
	var stderr bytes.Buffer

	code := Main([]string{
		"generate", "orm",
		"--config", configPath,
		"./...",
	}, &stdout, &stderr)

	if code != 2 {
		t.Fatalf("expected exit code 2, got %d", code)
	}
	if !strings.Contains(stderr.String(), "--config") {
		t.Fatalf("expected config error, got %q", stderr.String())
	}
}

func TestCommand_whenHelpRequested_shouldReturnSuccess(t *testing.T) {
	var stdout bytes.Buffer
	var stderr bytes.Buffer

	code := Main([]string{"generate", "orm", "--help"}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d", code)
	}
	if !strings.Contains(stdout.String(), "goark-orm generate orm [pattern] [flags]") {
		t.Fatalf("expected ORM help in stdout, got %q", stdout.String())
	}
	if stderr.Len() != 0 {
		t.Fatalf("stderr should be empty, got %q", stderr.String())
	}
}

func TestCommand_whenVersionRequested_shouldPrintVersion(t *testing.T) {
	var stdout bytes.Buffer
	var stderr bytes.Buffer

	code := Command{Out: &stdout, Err: &stderr, Version: "test"}.Run([]string{"--version"})

	if code != 0 {
		t.Fatalf("expected exit code 0, got %d", code)
	}
	if strings.TrimSpace(stdout.String()) != "goark-orm test" {
		t.Fatalf("unexpected version output %q", stdout.String())
	}
	if stderr.Len() != 0 {
		t.Fatalf("stderr should be empty, got %q", stderr.String())
	}
}

func writeORMFixture(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	writeORMFixtureAt(t, dir)
	return dir
}

func writeORMFixtureAt(t *testing.T, dir string) {
	t.Helper()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir ORM fixture failed: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "mapper.go"), []byte(`package sample

import "context"

//goark-orm:entity(table="sys_user")
type User struct {
	ID int64 `+"`"+`goark-orm:"column='id';primary-key=true;auto-increment=true"`+"`"+`
	Name string `+"`"+`goark-orm:"column='name'"`+"`"+`
}

//goark-orm:mapper(namespace="system.user.UserMapper")
type UserMapper interface {
	//goark-orm:select(sql="select id, name from sys_user where id = #{id}")
	FindByID(ctx context.Context, id int64) (*User, error)
}
`), 0o644); err != nil {
		t.Fatalf("write ORM source failed: %v", err)
	}
}
