package ormgen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"goark.dev/orm"
)

// Generate 扫描单个 Go package 并生成 ORM 源码。
func Generate(spec GenerateSpec) ([]byte, error) {
	model, err := ScanPackage(spec)
	if err != nil {
		return nil, err
	}
	return Render(model)
}

// Render 将扫描模型渲染为 Go 源码。
func Render(model *PackageModel) ([]byte, error) {
	if model == nil {
		return nil, fmt.Errorf("goark-orm: package model is nil")
	}
	var builder bytes.Buffer
	builder.WriteString("// Code generated by goark-orm; DO NOT EDIT.\n")
	builder.WriteString("// 本文件由 goark-orm 生成，请勿手工修改。\n\n")
	builder.WriteString("package ")
	builder.WriteString(model.PackageName)
	builder.WriteString("\n\n")
	writeImports(&builder, model)
	writeRegisterFunction(&builder, model)
	writeHelperFunctions(&builder, model)
	for _, mapper := range model.Mappers {
		writeMapperImplementation(&builder, model, mapper)
	}
	formatted, err := format.Source(builder.Bytes())
	if err != nil {
		return nil, fmt.Errorf("goark-orm: format generated source failed: %w\n%s", err, builder.String())
	}
	return formatted, nil
}

func writeImports(builder *bytes.Buffer, model *PackageModel) {
	builder.WriteString("import (\n")
	if len(model.Mappers) > 0 {
		builder.WriteString(strconv.Quote("context"))
		builder.WriteByte('\n')
	}
	builder.WriteString("orm ")
	builder.WriteString(strconv.Quote("goark.dev/orm"))
	builder.WriteByte('\n')
	builder.WriteString(")\n\n")
}

func writeRegisterFunction(builder *bytes.Buffer, model *PackageModel) {
	builder.WriteString("func RegisterGoarkORMMetadata(registry *orm.Registry) error {\n")
	for _, entity := range model.Entities {
		builder.WriteString("if err := registry.RegisterEntity(")
		writeEntityMeta(builder, entity)
		builder.WriteString("); err != nil {\nreturn err\n}\n")
	}
	for _, mapper := range model.Mappers {
		builder.WriteString("if err := registry.RegisterMapper(")
		writeMapperMeta(builder, mapper)
		builder.WriteString("); err != nil {\nreturn err\n}\n")
	}
	builder.WriteString("return nil\n")
	builder.WriteString("}\n\n")
}

func writeEntityMeta(builder *bytes.Buffer, entity EntityModel) {
	builder.WriteString("orm.EntityMeta{")
	builder.WriteString("TypeName:")
	builder.WriteString(strconv.Quote(entity.TypeName))
	builder.WriteString(",Table:")
	builder.WriteString(strconv.Quote(entity.Table))
	builder.WriteString(",Columns:[]orm.ColumnMeta{")
	for _, column := range entity.Columns {
		writeColumnMeta(builder, column)
		builder.WriteByte(',')
	}
	builder.WriteString("}}")
}

func writeColumnMeta(builder *bytes.Buffer, column ColumnModel) {
	builder.WriteString("{")
	writeStringField(builder, "FieldName", column.FieldName)
	writeStringField(builder, "FieldType", column.FieldType)
	writeStringField(builder, "ColumnName", column.ColumnName)
	writeBoolField(builder, "PrimaryKey", column.PrimaryKey)
	writeBoolField(builder, "AutoIncrement", column.AutoIncrement)
	if column.Nullable != nil {
		builder.WriteString("Nullable: goarkORMBoolPtr(")
		builder.WriteString(strconv.FormatBool(*column.Nullable))
		builder.WriteString("),")
	}
	if column.Size != nil {
		builder.WriteString("Size: goarkORMIntPtr(")
		builder.WriteString(strconv.Itoa(*column.Size))
		builder.WriteString("),")
	}
	writeStringField(builder, "DBType", column.DBType)
	writeStringField(builder, "DefaultValue", column.DefaultValue)
	writeStringField(builder, "TypeHandler", column.TypeHandler)
	writeBoolField(builder, "Version", column.Version)
	writeBoolField(builder, "SoftDelete", column.SoftDelete)
	writeBoolField(builder, "CreatedAt", column.CreatedAt)
	writeBoolField(builder, "UpdatedAt", column.UpdatedAt)
	builder.WriteString("}")
}

func writeMapperMeta(builder *bytes.Buffer, mapper MapperModel) {
	builder.WriteString("orm.MapperMeta{")
	writeStringField(builder, "TypeName", mapper.TypeName)
	writeStringField(builder, "Namespace", mapper.Namespace)
	writeStringField(builder, "XML", mapper.XML)
	writeStringField(builder, "ImplTypeName", mapper.ImplTypeName)
	builder.WriteString("ResultMaps:[]orm.ResultMapMeta{")
	for _, resultMap := range mapper.ResultMaps {
		builder.WriteString("{")
		writeStringField(builder, "ID", resultMap.ID)
		writeStringField(builder, "TypeName", resultMap.TypeName)
		builder.WriteString("Fields:[]orm.ResultFieldMeta{")
		for _, field := range resultMap.Fields {
			builder.WriteString("{")
			writeStringField(builder, "Property", field.Property)
			writeStringField(builder, "Column", field.Column)
			writeBoolField(builder, "ID", field.ID)
			writeStringField(builder, "TypeHandler", field.TypeHandler)
			builder.WriteString("},")
		}
		builder.WriteString("}},")
	}
	builder.WriteString("},")
	builder.WriteString("Statements:[]orm.StatementMeta{")
	for _, statement := range mapper.Statements {
		writeStatementMeta(builder, statement)
		builder.WriteByte(',')
	}
	builder.WriteString("}}")
}

func writeStatementMeta(builder *bytes.Buffer, statement StatementModel) {
	builder.WriteString("{")
	writeStringField(builder, "ID", statement.ID)
	writeStringField(builder, "Namespace", statement.Namespace)
	writeStringField(builder, "FullName", statement.FullName)
	builder.WriteString("Command:orm.StatementCommand(")
	builder.WriteString(strconv.Quote(string(statement.Command)))
	builder.WriteString("),")
	builder.WriteString("Source:orm.StatementSource(")
	builder.WriteString(strconv.Quote(string(statement.Source)))
	builder.WriteString("),")
	writeStringField(builder, "SQL", statement.SQL)
	writeStringField(builder, "ResultMap", statement.ResultMap)
	writeStringField(builder, "ResultType", statement.ResultType)
	writeStringField(builder, "ParameterType", statement.ParameterType)
	writeBoolField(builder, "UseGeneratedKeys", statement.UseGeneratedKeys)
	writeStringField(builder, "KeyProperty", statement.KeyProperty)
	if len(statement.DynamicSQL) > 0 {
		builder.WriteString("DynamicSQL:")
		writeDynamicSQLNodes(builder, statement.DynamicSQL)
		builder.WriteByte(',')
	}
	builder.WriteString("}")
}

func writeDynamicSQLNodes(builder *bytes.Buffer, nodes []orm.DynamicSQLNode) {
	builder.WriteString("[]orm.DynamicSQLNode{")
	for _, node := range nodes {
		builder.WriteString("{")
		builder.WriteString("Kind:")
		builder.WriteString(dynamicSQLKindExpression(node.Kind))
		builder.WriteByte(',')
		writeStringField(builder, "Text", node.Text)
		writeStringField(builder, "Test", node.Test)
		writeStringField(builder, "Prefix", node.Prefix)
		writeStringField(builder, "Suffix", node.Suffix)
		writeStringField(builder, "PrefixOverrides", node.PrefixOverrides)
		writeStringField(builder, "SuffixOverrides", node.SuffixOverrides)
		writeStringField(builder, "Collection", node.Collection)
		writeStringField(builder, "Item", node.Item)
		writeStringField(builder, "Index", node.Index)
		writeStringField(builder, "Open", node.Open)
		writeStringField(builder, "Close", node.Close)
		writeStringField(builder, "Separator", node.Separator)
		writeStringField(builder, "RefID", node.RefID)
		if len(node.Children) > 0 {
			builder.WriteString("Children:")
			writeDynamicSQLNodes(builder, node.Children)
			builder.WriteByte(',')
		}
		builder.WriteString("},")
	}
	builder.WriteString("}")
}

func dynamicSQLKindExpression(kind orm.DynamicSQLNodeKind) string {
	switch kind {
	case orm.DynamicSQLNodeText:
		return "orm.DynamicSQLNodeText"
	case orm.DynamicSQLNodeIf:
		return "orm.DynamicSQLNodeIf"
	case orm.DynamicSQLNodeWhere:
		return "orm.DynamicSQLNodeWhere"
	case orm.DynamicSQLNodeSet:
		return "orm.DynamicSQLNodeSet"
	case orm.DynamicSQLNodeTrim:
		return "orm.DynamicSQLNodeTrim"
	case orm.DynamicSQLNodeForeach:
		return "orm.DynamicSQLNodeForeach"
	case orm.DynamicSQLNodeChoose:
		return "orm.DynamicSQLNodeChoose"
	case orm.DynamicSQLNodeWhen:
		return "orm.DynamicSQLNodeWhen"
	case orm.DynamicSQLNodeOtherwise:
		return "orm.DynamicSQLNodeOtherwise"
	case orm.DynamicSQLNodeInclude:
		return "orm.DynamicSQLNodeInclude"
	default:
		return "orm.DynamicSQLNodeKind(" + strconv.Quote(string(kind)) + ")"
	}
}

func writeStringField(builder *bytes.Buffer, name string, value string) {
	if value == "" {
		return
	}
	builder.WriteString(name)
	builder.WriteByte(':')
	builder.WriteString(strconv.Quote(value))
	builder.WriteByte(',')
}

func writeBoolField(builder *bytes.Buffer, name string, value bool) {
	if !value {
		return
	}
	builder.WriteString(name)
	builder.WriteString(":true,")
}

func writeMapperImplementation(builder *bytes.Buffer, model *PackageModel, mapper MapperModel) {
	builder.WriteString("type ")
	builder.WriteString(mapper.ImplTypeName)
	builder.WriteString(" struct {\nsession orm.Session\n}\n\n")
	builder.WriteString("func New")
	builder.WriteString(mapper.TypeName)
	builder.WriteString("(session orm.Session) ")
	builder.WriteString(mapper.TypeName)
	builder.WriteString(" {\nreturn &")
	builder.WriteString(mapper.ImplTypeName)
	builder.WriteString("{session: session}\n}\n\n")
	for _, method := range mapper.Methods {
		writeMapperMethod(builder, model, mapper, method)
	}
}

func writeMapperMethod(builder *bytes.Buffer, model *PackageModel, mapper MapperModel, method MethodModel) {
	builder.WriteString("func (m *")
	builder.WriteString(mapper.ImplTypeName)
	builder.WriteString(") ")
	builder.WriteString(method.Name)
	builder.WriteByte('(')
	writeParams(builder, method.Params)
	builder.WriteString(") (")
	builder.WriteString(method.ResultType)
	builder.WriteString(", error) {\n")
	argsExpr := namedArgsExpression(model, method)
	switch method.Statement.Command {
	case orm.StatementCommandSelect:
		builder.WriteString("var out ")
		builder.WriteString(method.ResultType)
		builder.WriteByte('\n')
		execMethod := "QueryOne"
		if strings.HasPrefix(strings.TrimSpace(method.ResultType), "[]") {
			execMethod = "Query"
		}
		builder.WriteString("err := m.session.")
		builder.WriteString(execMethod)
		builder.WriteByte('(')
		builder.WriteString(method.Params[0].Name)
		builder.WriteString(", ")
		builder.WriteString(strconv.Quote(method.Statement.FullName))
		builder.WriteString(", ")
		builder.WriteString(argsExpr)
		builder.WriteString(", &out)\n")
		builder.WriteString("return out, err\n")
	case orm.StatementCommandInsert, orm.StatementCommandUpdate, orm.StatementCommandDelete:
		builder.WriteString("result, err := m.session.Exec(")
		builder.WriteString(method.Params[0].Name)
		builder.WriteString(", ")
		builder.WriteString(strconv.Quote(method.Statement.FullName))
		builder.WriteString(", ")
		builder.WriteString(argsExpr)
		builder.WriteString(")\nif err != nil {\nreturn 0, err\n}\n")
		if method.Statement.Command == orm.StatementCommandInsert && method.Statement.UseGeneratedKeys {
			builder.WriteString("return result.LastInsertID, nil\n")
		} else {
			builder.WriteString("return result.RowsAffected, nil\n")
		}
	}
	builder.WriteString("}\n\n")
}

func writeParams(builder *bytes.Buffer, params []ParamModel) {
	for index, param := range params {
		if index > 0 {
			builder.WriteString(", ")
		}
		builder.WriteString(param.Name)
		builder.WriteByte(' ')
		builder.WriteString(param.Type)
	}
}

func namedArgsExpression(model *PackageModel, method MethodModel) string {
	pairs := make(map[string]string)
	for _, param := range method.Params[1:] {
		pairs[param.Name] = param.Name
	}
	if len(method.Params) == 2 {
		param := method.Params[1]
		entityName := normalizeTypeName(param.Type)
		for _, entity := range model.Entities {
			if entity.TypeName != entityName {
				continue
			}
			for _, column := range entity.Columns {
				pairs[column.FieldName] = param.Name + "." + column.FieldName
			}
		}
	}
	keys := make([]string, 0, len(pairs))
	for key := range pairs {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var builder strings.Builder
	builder.WriteString("orm.NamedArgs{")
	for _, key := range keys {
		builder.WriteString(strconv.Quote(key))
		builder.WriteByte(':')
		builder.WriteString(pairs[key])
		builder.WriteByte(',')
	}
	builder.WriteByte('}')
	return builder.String()
}

func writeHelperFunctions(builder *bytes.Buffer, model *PackageModel) {
	if !modelNeedsPointerHelpers(model) {
		return
	}
	builder.WriteString("func goarkORMBoolPtr(value bool) *bool {\nreturn &value\n}\n\n")
	builder.WriteString("func goarkORMIntPtr(value int) *int {\nreturn &value\n}\n\n")
}

func modelNeedsPointerHelpers(model *PackageModel) bool {
	for _, entity := range model.Entities {
		for _, column := range entity.Columns {
			if column.Nullable != nil || column.Size != nil {
				return true
			}
		}
	}
	return false
}

// DefaultOutputName 返回包级 ORM 生成文件默认名称。
func DefaultOutputName(packageName string) string {
	packageName = strings.TrimSpace(packageName)
	if packageName == "" {
		packageName = "package"
	}
	return filepath.Clean("zz_goark_orm_" + packageName + "_gen.go")
}

// DiscoverPackages 查找 pattern 指向的可扫描 Go package 目录。
func DiscoverPackages(pattern string) ([]string, error) {
	pattern = strings.TrimSpace(pattern)
	if pattern == "" {
		pattern = "."
	}
	if !strings.HasSuffix(pattern, "...") {
		return []string{filepath.Clean(strings.TrimSuffix(pattern, string(filepath.Separator)))}, nil
	}
	root := strings.TrimSuffix(pattern, "...")
	root = strings.TrimSuffix(root, "/")
	root = strings.TrimSuffix(root, "\\")
	if root == "" {
		root = "."
	}
	root = filepath.Clean(root)
	dirs := make([]string, 0)
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !entry.IsDir() {
			return nil
		}
		name := entry.Name()
		if name == ".git" || name == "vendor" {
			return filepath.SkipDir
		}
		hasPackage, err := directoryHasGoPackage(path)
		if err != nil {
			return err
		}
		if hasPackage {
			dirs = append(dirs, path)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(dirs)
	return dirs, nil
}

func directoryHasGoPackage(path string) (bool, error) {
	entries, err := filepath.Glob(filepath.Join(path, "*.go"))
	if err != nil {
		return false, err
	}
	for _, entry := range entries {
		base := filepath.Base(entry)
		if strings.HasSuffix(base, "_test.go") || strings.HasPrefix(base, "zz_goark_orm_") {
			continue
		}
		fset := token.NewFileSet()
		if _, err := parser.ParseFile(fset, entry, nil, parser.PackageClauseOnly); err == nil {
			return true, nil
		}
	}
	return false, nil
}
